### ISSUE TITLE
data.sql does create tables but does not fill them with demo data

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/demo-ecommerce#1]
The database dumps from the /dump/data/ directory are not included when installing pimcore with the ecommerce demo package resulting in empty tables (empty documents / assets / objects) and a non-working demo.

**Comment by fashxp** [comment]
right now, we import the data with LOAD DATA INFILE. you might need to enable this on you environment.

does this help you further?

**Comment by Cruiser13** [comment]
Thanks, I didn't notice that line. Looks like the infile loading failed during the install without further notice.
Running the commands manually imported the demo data just fine.

**Comment by mingfang** [comment]
Doesn't the usage of ```LOAD DATA INFILE``` imply that pimcore must be running on the same host as the database?
If so then this is not acceptable.  The database must be able to run remotely.
