### ISSUE TITLE
Instructions for LOAD DATA INLINE?

### ISSUE THREAD

**Issue by JohnDeegs** [pimcore/demo-ecommerce#11]
Hi all,

I'm trying to do the LOAD DATA INLINE fix but I'm confused as to the process I must use. I'm using MariaDB if that helps. From googling online all I can find is using the command on CSV files. Should this be done before installation or after? 

Thanks :)

**Comment by fashxp** [comment]
nono, not so complicated. just make sure, that your db user has the FILE permission ... should something like that: `GRANT FILE ON *.* TO 'YOUR-USER'@'localhost';"`
.. so that LOAD DATA INLINE can be executed.

**Comment by JohnDeegs** [comment]
Thanks for the speedy reply! Do I have to reinstall pimcore after doing this?

**Comment by fashxp** [comment]
no, the install process is as follows: 

- check if database user has necessary rights
- Download latest Pimcore 5 build & extract it
- Install this package via composer: `require pimcore/demo-ecommerce --no-scripts`
- Install pimcore (via web or CLI installer) - it should now list this install profile as available

**Comment by JohnDeegs** [comment]
It's now working thankfully, however I have a separate issue.

![noscripts](https://user-images.githubusercontent.com/14318845/30437705-2f15856a-9967-11e7-8e13-84410a552a42.png)

I think I know why this error is happening. When I run the composer command to get the ecommerce demo it doesn't allow me to use --no-scripts, as it says it's not a valid command.

![ecomm](https://user-images.githubusercontent.com/14318845/30437778-6560c40e-9967-11e7-8ba8-94d85eb59b3f.png)

When I ran the above command without --no-scripts it installed fine. But I guess it errors the documents. Any ideas?

**Comment by fashxp** [comment]
it seems to be related to this one: https://github.com/pimcore/pimcore/issues/1967

**Comment by JohnDeegs** [comment]
Running the command in the link ..

`bin/console assets:install --symlink `--relative``

Worked. I'm not sure why but it's got rid of the error for now. My PHP version is 7.1 and I'm using apache and mariadb if that helps with any fixes.

**Comment by maff** [comment]
The installer currently does not execute the `assets:install` step. Until this is fixed (see https://github.com/pimcore/pimcore/issues/1974) I added it to the list of installation steps in the readme.

**Comment by maff** [comment]
@JohnDeegs regarding composer `--no-scripts`: what version of composer are you running?
