### ISSUE TITLE
You have requested a non-existent parameter "google_client_id".

### ISSUE THREAD

**Issue by GianniRiemslagh** [pimcore/demo-ecommerce#17]
When starting the install with ecommerce Demo data I get this error: 

ERROR(s) (please see var/installer/logs for details):
You have requested a non-existent parameter "google_client_id".

(1/1) ParameterNotFoundException
You have requested a non-existent parameter "google_client_id".

**Comment by GianniRiemslagh** [comment]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "google_client_id". in /var/
  web/vd7474/public_html/demo-ecommerce/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
  Stack trace:
  #0 /var/web/vd7474/public_html/demo-ecommerce/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Co
  mponent\DependencyInjection\ParameterBag\ParameterBag->get('google_client_i...')
  #1 /var/web/vd7474/public_html/demo-ecommerce/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(217): Symfony\Component\Depen
  dencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('google_client_i...')
  #2 /var/web/vd7474/public_html/demo-ecommerce/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\Depen
  dencyInjection\ParameterBag\ParameterBag->re in /var/web/vd7474/public_html/demo-ecommerce/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/P
  arameterBag.php on line 100

**Comment by fashxp** [comment]
hmm, strange... which version did you try? did you try with dev-master? 
is following file present in your installation? 
https://github.com/pimcore/demo-ecommerce/blob/master/app/config/parameters.yml

**Comment by fashxp** [comment]
closed due to inactivity
