### ISSUE TITLE
A little help here pls.

### ISSUE THREAD

**Issue by keondev** [pimcore/demo-ecommerce#19]
Hi, Im a newbie using pimcore and I wanted to use this ecommerce template
can you please help me how to install it on my pimcore website?
Hope someone help me thanks in advance.

Here is my website http://www.vendify.net/

**Comment by keondev** [comment]
do I just need to upload the files somewhere else, like on /pimcore/ folder and activate it on pimcore dashboard? 
I tried to upload it on extension manager but nothing happened.
Please help

**Comment by fashxp** [comment]
Hi,
please have a look at https://github.com/pimcore/demo-ecommerce/blob/master/README.md 

* Install this package via composer: ```require pimcore/demo-ecommerce --no-scripts```

* Install Pimcore (via web or CLI installer) - it should now list this install profile as available

* Execute the following command to symlink any assets from bundles into your document root (you can omit the symlink and relative options if that fits your environment better): ```$ bin/console assets:install --symlink --relative```

For further assistance please consult our forums https://talk.pimcore.org/ - github issues should be used as issue tracker only. Thank you very much.
