### ISSUE TITLE
demo-ecommerce error after install

### ISSUE THREAD

**Issue by elwininc** [pimcore/demo-ecommerce#24]
Hello
After executing composer commond to install demo-ecommerce
An exception occurred while executing 'SELECT id FROM targeting_target_groups UNION SELECT id FROM targeting_rules LIMIT 1':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore5.targeting_target_groups' doesn't exist

How to solve it?

the vision is 5.1.0-alpha  ecommerce is 1.4.2

Thank you
elwin

**Comment by fashxp** [comment]
do you mean ecommerce-demo version 1.4.1? 1.4.2 isn't released yet, isn't it? 

what were your steps exactly? our demos are build the same way as described in install docs of ecommerce demo ... and they work well.

**Comment by elwininc** [comment]
Hello
this is my step for installation:
1.I download pimcore-stable.zip from pimcore.org, it is 5.1.0-alpha 
2.unzip it.
3.composer require pimcore/demo-ecommerce --no-scripts
3.chown -R apache:apache /the directory/
4.chmod 775 -R /the /directory/
5. install on web http://ip/install
6, install finished,no error issued.

frontend display error like last message
backend is ok,but prompt the error when we enter.

I re- install vision 5.0.1-alpha ,it seem that it is same error,without install ecommerce.
Now I install vision 5.0.4 , the work is fine. I think that the env is ok for pimcore
it only 3 Yellow exclamation markv(recommend but no required)

Thank you

**Comment by elwininc** [comment]
I try to install several time ,also another guy install it again, same problem
I do not make sure if what is wrong on my install step

**Comment by fashxp** [comment]
can you have a look at the database? does the table `targeting_target_groups` exist? is there any data in other tables like `objects` or so?

**Comment by fashxp** [comment]
could you try the 5.1.0 release ... should be fixed now.

**Comment by elwininc** [comment]
Hello

Update the latest vision, it work fine, Thank you

2018-01-02 17:40 GMT+08:00 Christian Fasching <notifications@github.com>:

**Comment by fashxp** [comment]
ok, was a pimcore problem, not install-profile demo-ecommerce.
