### ISSUE TITLE
"Data Objects \ Field-Collections \ Filter* \ field" what kind of component?

### ISSUE THREAD

**Issue by voganu** [pimcore/demo-ecommerce#27]
In the demo version, Data Objects \ Field-Collections \ Filter * has a 'field' component, but it does not have the ability to edit it. There are no properties at all.

**Comment by fashxp** [comment]
this component gives you the possibility to select fields that are available in the product index: 
![image](https://user-images.githubusercontent.com/8792145/35802350-05c74dae-0a70-11e8-9652-5d0a6e6fd63f.png)

see also https://pimcore.com/docs/5.0.x/Development_Documentation/E-Commerce_Framework/Filter_Service.html#page_2-Setting-up-FilterDefinition-Objects

**Comment by fashxp** [comment]
what do you mean with you cannot edit it?

**Comment by voganu** [comment]
Settings -> Data Objects -> Field-Collections -> FilterSelection -> field has no properties! How to add this component to the field collections?

**Comment by fashxp** [comment]
do you have a screenshot for us? I cannot follow you, sorry

**Comment by voganu** [comment]
![image](https://user-images.githubusercontent.com/36076787/35804850-1daef720-0a82-11e8-9510-1f3b61149dec.png)

**Comment by fashxp** [comment]
ahh, now I get you ...
this should look like this (see also our advanced demo): 
![image](https://user-images.githubusercontent.com/8792145/35805006-5cc84234-0a7a-11e8-87b8-83e432e51618.png)

is the ecommerce framework bundle activated in extension manager?
looks like the js file for the datatype is missing.

**Comment by voganu** [comment]
![image](https://user-images.githubusercontent.com/36076787/35805085-22ab8044-0a83-11e8-8ade-f348aa2d2ab4.png)

**Comment by fashxp** [comment]
can you try to activate dev mode in system settings, reload pimcore and then have a closer look at the error message in console. 
then you should see the non minified js files. 
other steps to solve the problem could be
- clear cache
- clear temporary files
- clear browser cache
and try to reload pimcore.

**Comment by voganu** [comment]
I've implemented all of your recommendations, but the problem has remained
![image](https://user-images.githubusercontent.com/36076787/35807321-106d135e-0a8b-11e8-9ec5-e365f9123064.png)

**Comment by fashxp** [comment]
are these files available? 
![image](https://user-images.githubusercontent.com/8792145/35809388-bfc67a8c-0a88-11e8-8199-fde65eb26650.png)

if not, run the `asset:install` command

**Comment by voganu** [comment]
![image](https://user-images.githubusercontent.com/36076787/35920509-b98dfa66-0c20-11e8-93a4-45bb134264b9.png)

**Comment by fashxp** [comment]
did you try to run the `asset:install` command? 
does this problem still exists in lastest versions?
