### ISSUE TITLE
Syntax error or access violation PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist

### ISSUE THREAD

**Issue by nicogasque** [pimcore/demo-ecommerce#28]
Hello,

I have the following error in Documents --> Home or any others documents.

-----------------------------
Server threw exception - could not perform action. Please reload the admin interface and try again.

Timestamp: Fri Feb 16 2018 16:00:46 GMT+0100 (Central Europe Standard Time)
Status: 500 | Internal Server Error
URL: /admin/customermanagementframework/segment-assignment/inheritable-segments?id=3&type=document&_dc=1518793243795
Method: GET
Message: An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [4]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION pimo_data.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist
-----------------------------

in Symfony 

------------------------------
Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [4]: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION pimo_data.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist" at /var/www/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115
------------------------------

An idea?

**Comment by fashxp** [comment]
does the table exist in your installation? 
PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS

**Comment by fashxp** [comment]
closed due to inactivity
