### ISSUE TITLE
Can't save a class

### ISSUE THREAD

**Issue by Gaby033** [pimcore/demo-ecommerce#29]
I installed this demo by following your instructions and everything went well during the installation process.

However I didn't manage to disable the bundle AdvancedObjectSearchBundle (not really explained) so I had to install elasticsearch (current version : 6.2, on Debian 8.9).

Here is a screenshot of what I got when I click on save.
![image](https://user-images.githubusercontent.com/37073350/38617687-f3f80090-3d97-11e8-83d7-7d2bbc4cedb7.png)

Here is the var/logs/prod.log :
[error-pimcore-save.txt](https://github.com/pimcore/demo-ecommerce/files/1898844/error-pimcore-save.txt)

Also, is it normal to not have "Product attributes" and "Categories" in the left panel ? Like on the demo version : https://demo-advanced.pimcore.org.

**Comment by fashxp** [comment]
Hi,
which version of ElasticSearch are you using? We would need ES5 - ES6 had some breaking changes. 

Deactivation of this bundle should be possible the standard way like pimcore bundles can be deactivated: 
![image](https://user-images.githubusercontent.com/8792145/38631118-22ae2c68-3db9-11e8-9cf1-ccf1ab620199.png)


Data should be the same as within the the demo-advanced instance.

**Comment by fashxp** [comment]
is there any other data visible? 
there is nothing hidden by default - either everything is visible, or import of data failed completely during install.

**Comment by fashxp** [comment]
closed due to inactivity
