### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by reneglauser** [pimcore/demo-ecommerce#3]
Hi
I have problems installing dem pimcore demo-ecommerce. Where can I find die install.php mentioned in your description?
Regards
René

**Comment by fashxp** [comment]
file is `web/install.php`

add following line to store in line 434:
`["demo-ecommerce", "Ecommerce Demo Applikation"]`

**Comment by fashxp** [comment]
added a bit more detailed description, hope this helps further? 

but we will improve this installation anyway...
