### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/demo-ecommerce#30]
Hi,
I have downloaded this repo in pimcore 5 but when I run the install with CMS Demo it gives an Error as 
```
InvalidArgumentException
The class "HWI\Bundle\OAuthBundle\HWIOAuthBundle" does not exist
```
Just wondering whether something I am doing wrong here.

Also, it does not show any separate installer profile just as fresh pimcore installation has.

**Comment by fashxp** [comment]
hmm, I'm afraid I cannot follow you. What are your exact steps?

**Comment by vinitchopra12** [comment]
Sorry, I haven't follow the Compose command so it throws an Error. Kindly ignore the previous error.

Now I have installed the pimcore using Ecommerce Demo Installer but it does not shows up any data in it. Although I have tried to Enabled the ecommerce bundle from extension but it gives an error as
```
URL: /admin/extensionmanager/admin/install
Message: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```
Please see the screenshot: https://www.awesomescreenshot.com/image/3296807/b4db52e27cd2034c196593193ec2b814

My running this in MySQL v5.7.21and PHP v7.0.28.

**Comment by fashxp** [comment]
Ah, the demo uses the customer management framework and therefore it needs MariaDB. 
I just added a hint in the readme: https://github.com/pimcore/demo-ecommerce/blob/master/README.md#installation-requirements

We are planning to remove that dependency, but currently there is no other solution. Sorry.
