### ISSUE TITLE
still problem with install.php

### ISSUE THREAD

**Issue by reneglauser** [pimcore/demo-ecommerce#4]
Thanks for your reply. But I have still problem installing the demo. Inside the web-directory ther are only two subdirectories static and var. Do you mean the web directory of the unziped file master.zip or do you mean another web-directory?

**Comment by reneglauser** [comment]
i solved my problem: I tried to install in v 4.6. Then switched to v 5 and everything is clear now.
thanks

**Comment by fashxp** [comment]
ah ok, yes it is for Pimcore 5 only :) 
I added a note to the readme file.
