### ISSUE TITLE
Error Installation PIMCORE 5 on Centos 7

### ISSUE THREAD

**Issue by antocipi** [pimcore/demo-ecommerce#41]
Hi,

I have a problem at 90% when install PIMCORE on CENTOS 7

Follow i show my problem

Can someone help me for resolve this problem?

Thanks in advance.

Best REGARDS 
___________________________________________________________________________________________________

#pimcore_install

Running installation. You can find a detailed install log in var/installer/logs/dev.log

Mark existing migrations as done ...

  9/10 [=========================>--]  90%

 Trying to install assets as relative symbolic links.

 --- ------------------------------------------ ------------------
      Bundle                                     Method / Error
 --- ------------------------------------------ ------------------
  ✔   PimcoreAdminBundle                         relative symlink
  ✔   PimcoreCoreBundle                          relative symlink
  ✔   PimcoreEcommerceFrameworkBundle            relative symlink
  ✔   OutputDataConfigToolkitBundle              relative symlink
  ✔   Web2PrintToolsBundle                       relative symlink
  ✔   PimcoreCustomerManagementFrameworkBundle   relative symlink
  ✔   ObjectMergerBundle                         relative symlink
 --- ------------------------------------------ ------------------

 [OK] All assets were successfully installed.

 **[ERROR] The following errors were encountered during installation

 * An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':

Warning: Error while sending QUERY packet. PID=6367**

**Comment by brusch** [comment]
Ensure you are allowed to run the following query (as it is mentioned in the error message): 
`SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'`

**Comment by antocipi** [comment]
Hi Brusch,

Thanks for your immediate answer.

Yes i can to do the query, infact i have try in mysql at to execute the quey  SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' and work **but during installation i have a problem**

How can i to do for resolve this problem ?

Let me know for me is very important.

Thanks in advance.

**Comment by brusch** [comment]
@antocipi please ensure you're running the query using the same user/permissions. 
Otherwise i have no idea why it's not working, ... if there's anything we can do/fix, just let us know. Thanks!

**Comment by antocipi** [comment]
Hi Brush,

the user is the same.

In log file i have found this:

 **app.ERROR: Symfony\Component\Debug\Exception\ContextErrorException: Warning: Error while sending QUERY packet. PID=6367 in /PimCore/CIPI/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107 Stack trace: #0 /PimCore/CIPI/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(940): Doctrine\DBAL\Driver\PDOConnection->query('SHOW FULL TABLE...') #**

Can you help me , with this log ?

Let me know, and thanks in advance.

Best Regards

**Comment by brusch** [comment]
Haven't seen this error before... seems to be specific to your environment.

**Comment by antocipi** [comment]
I have
- **Server version: Apache/2.4.6 (CentOS)**
- MariaDB  version: 10.0.37
- Centos 7 operating system
- PHP 7.1.23 

Are you know how can i resolve this problem ?

Thanks in advance.

**Comment by brusch** [comment]
No

**Comment by antocipi** [comment]
Hi Brush,

i have reinstall all but have a same problem ?

who can help me to resolve this problem ?

Let me know.

Thanks in advance

Best Regards
Antonello
