### ISSUE TITLE
Error Installation 90%:   SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':  Warning: Error 

### ISSUE THREAD

**Issue by antocipi** [pimcore/demo-ecommerce#42]
Hi,

meantime i install Pimcore with Composer, ii have this problema at 90% of installation.

Because ?

Can someone help me ?

Let me know is very important.

Best regards.
Antonello

**Comment by avneesh-webkul** [comment]
Hi,
I'm facing the issue, but at 60% only. Other demos are working fine, but this one stuck at 60% every time while **running database setup** and does not continue. I've tried many times to install it, but no luck.
Thanks

**Comment by fashxp** [comment]
is there some more information available? 
at our systems, installation runs through

**Comment by fashxp** [comment]
an how? :)

**Comment by avneesh-webkul** [comment]
I was running mariadb in docker container, so there were some mapping issue with that.
Now it's working perfectly fine :)

**Comment by fashxp** [comment]
👍 thanks for sharing
