### ISSUE TITLE
Issue in removing demo sample data.

### ISSUE THREAD

**Issue by jatinrathod17** [pimcore/demo-ecommerce#43]
When i am removing demo sample data provided by the time of installation and creating new data it is creating issue with product detail page and giving error for product link.

Please let me know how to remove demo sample data.

**Comment by brusch** [comment]
Just install the skeleton: https://github.com/pimcore/skeleton

**Comment by jatinrathod17** [comment]
will this include e-commerce bundle in it?

**Comment by jatinrathod17** [comment]
yes, but if i have to remove current demo data from the demo-ecommerce package than it is possible?
