### ISSUE TITLE
Bundle or Grouped Product

### ISSUE THREAD

**Issue by jatinrathod17** [pimcore/demo-ecommerce#45]
Hello,

How to create bundled or grouped product in pimcore e-commerce?

Please guide me.

**Comment by brusch** [comment]
You have the choice: 
https://talk.pimcore.org/
https://pimcore.com/docs/5.x/index.html
https://gitter.im/pimcore/pimcore

but please don't use GitHub for requesting support.
Thanks

**Comment by jatinrathod17** [comment]
ok will take care of this next time.
