### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by reneglauser** [pimcore/demo-ecommerce#5]
Hi
I face again some installation problems. Please have a look at the following images

https://cloud.swisslux.ch/index.php/s/2w9LEswf2x8M6h5
https://cloud.swisslux.ch/index.php/s/a6ayuhOcG2I4s6j

Do I miss some dependencies?

Thanks René

**Comment by fashxp** [comment]
first screen seems to say, that the install-profile was not found. 
did you extract the demo-ecommerce source files (git repository) into the folder `/install-profiles/demo-ecommerce` of your pimcore 5 installation?

**Comment by fashxp** [comment]
second screen might be a followup problem

**Comment by reneglauser** [comment]
I extracted to the content to ./install-profiles/demo-ecommerce-master, then I renamed the folder to "demo-ecommerce", so the folder does exist as mentioned in install.php with ["demo-ecommerce", "Ecommerce Demo Applikation"]

**Comment by reneglauser** [comment]
I succeeded to install de demo know, but when I login with admin I get the following error. Is this maybe related to the ecommerce-demo? the installation of cms-demo works normal...


Error
Server threw exception - could not perform action. Please reload the admin interface and try again.

Status: 500 | Internal Server Error
URL: /admin/asset/tree-get-root
Message: Call to a member function isAllowed() on null
Trace: [
  {
    "function": "treeGetRootAction",
    "class": "Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\ElementControllerBase",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      }
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
    "line": 153,
    "function": "call_user_func_array",
    "args": [
      [
        {},
        "treeGetRootAction"
      ],
      [
        {
          "attributes": {},
          "request": {},
          "query": {},
          "server": {},
          "files": {},
          "cookies": {},
          "headers": {}
        }
      ]
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
    "line": 68,
    "function": "handleRaw",
    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      },
      1
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
    "line": 171,
    "function": "handle",
    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      },
      1,
      true
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/web/app.php",
    "line": 21,
    "function": "handle",
    "class": "Symfony\\Component\\HttpKernel\\Kernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      }
    ]
  }
]
OK
Error
Server threw exception - could not perform action. Please reload the admin interface and try again.

Status: 500 | Internal Server Error
URL: /admin/object/tree-get-root
Message: Call to a member function isAllowed() on null
Trace: [
  {
    "function": "treeGetRootAction",
    "class": "Pimcore\\Bundle\\AdminBundle\\Controller\\Admin\\ElementControllerBase",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      }
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
    "line": 153,
    "function": "call_user_func_array",
    "args": [
      [
        {},
        "treeGetRootAction"
      ],
      [
        {
          "attributes": {},
          "request": {},
          "query": {},
          "server": {},
          "files": {},
          "cookies": {},
          "headers": {}
        }
      ]
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
    "line": 68,
    "function": "handleRaw",
    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      },
      1
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
    "line": 171,
    "function": "handle",
    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      },
      1,
      true
    ]
  },
  {
    "file": "/pimcore_projects/pimcore_shop/web/app.php",
    "line": 21,
    "function": "handle",
    "class": "Symfony\\Component\\HttpKernel\\Kernel",
    "type": "->",
    "args": [
      {
        "attributes": {},
        "request": {},
        "query": {},
        "server": {},
        "files": {},
        "cookies": {},
        "headers": {}
      }
    ]
  }
]

**Comment by fashxp** [comment]
what was wrong so that you know were able to contine the installation? 

is there any data in objects table(s)?

**Comment by reneglauser** [comment]
no, it seems that object tables are empty.....

**Comment by fashxp** [comment]
yea, this is another drawback of the current installation process: 
the database user needs the permission FILE in order to install the demo data. 
can you provide that and try the installation once more?

**Comment by reneglauser** [comment]
I tried that but still got the same problem....

**Comment by reneglauser** [comment]
I used this command: GRANT FILE ON *.* TO 'pimuser'@'%';
is this correct?

**Comment by fashxp** [comment]
have a look  at 
https://github.com/pimcore/demo-ecommerce/blob/master/dump/data.sql#L2626-L2626

These statements are executed whereas `~~DOCUMENTROOT~~` document root is replaced with your project root directory. you could just try to execute such an statement in order to make sure it works. 
What also is important - your mysql instance need to have access to these files. 

As I said earlier, we are searching for a better way to get lots of data into the database during install, right now we didn't had a better idea so far. 
Ideas and suggestions are always welcome :)

**Comment by reneglauser** [comment]
Thanks....no I solved the problem. The following statement did the trick:

grant file on *.* to pimuser@localhost identified by 'password';

But now I have the last problem, that I get the following error when I click on a document:

https://cloud.swisslux.ch/index.php/s/oPzzZKfOiGMWSjC

Is this maybe relatet to the demo data or something else?`

Thanks again
René

**Comment by reneglauser** [comment]
I also have problems when I do a "composer update" after installation of the demo-data. I get the following errors:
https://cloud.swisslux.ch/index.php/s/ddvdaEyrT11jFO6

Do you have any Idea what happens here?

Thanks again
René

**Comment by fashxp** [comment]
hmm, not really sorry

**Comment by fashxp** [comment]
could you please retry with latest build. 
should work now again.

**Comment by killerminds01** [comment]
I am also facing the same errors

Status: 500 | Internal Server Error
URL: /admin/asset/tree-get-root
URL: /admin/object/tree-get-root
URL: /admin/document/tree-get-root

any idea ?

**Comment by fashxp** [comment]
any log entries in php or webserver log? 
are there any entries in the object table?

**Comment by MarScheff** [comment]
Just as an FYI, I did have the same problem, no data in the system.
I had all the needed rights, but my MySQL server was not running on the same server as the Apache. So the CSV file have not been found.

I think, if you would use 
`LOAD DATA LOCAL INFILE`
instead of
`LOAD DATA INFILE`
it should work in both cases.

I did copy the files to my local machine, changed the SQLs and imported the files via MySQL WorkBench. I hope, that helps people having the same problem.

**Comment by mingfang** [comment]
Yes the correct way is to use ```LOAD DATA LOCAL INFILE```.
However when I change data.sql to use that I was getting a forbidden error.
I believe the PDO init code must enable it.

My hack around for this problem is, after running the normal installation steps, I run these commands...
```
sed -i "s|INFILE|LOCAL INFILE|g" /var/www/pimcore/vendor/pimcore/demo-ecommerce/dump/data.sql
sed -i "s|~~DOCUMENTROOT~~|/var/www/pimcore|g" /var/www/pimcore/vendor/pimcore/demo-ecommerce/dump/data.sql
mysql -h "$PIMCORE_INSTALL_MYSQL_HOST_SOCKET" -u "$PIMCORE_INSTALL_MYSQL_USERNAME" -p"$PIMCORE_INSTALL_MYSQL_PASSWORD" "$PIMCORE_INSTALL_MYSQL_DATABASE" < /var/www/pimcore/vendor/pimcore/demo-ecommerce/dump/data.sql
```

It's ugly but it works.
It took me 2 days to figure it out so hopefully it'll save you some time.
