### ISSUE TITLE
Bug when opening the print-document in `katalog`

### ISSUE THREAD

**Issue by ekrimbacher** [pimcore/demo-ecommerce#51]
When  visiting the printcontainer ‘katalog’ in the perspective ‘Katalog’ I receive the following error:
<img width="640" alt="error" src="https://user-images.githubusercontent.com/45061558/53010632-b0c79f80-343e-11e9-915a-0885dfb3bdd6.png">

It seems that there is something broken in the demo, it only appears while I try to open a print-document not by normal documents.

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/pimcore/issues/3982
