### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dennistiboni** [pimcore/demo-ecommerce#6]
Hi,
i have tried to install demo-ecommerce package, but the installer return this error:

Fatal error:  Interface 'Zend_Paginator_Adapter_Interface' not found in /var/www/public_html/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/IProductList.php on line 24

![schermata 2017-06-28 alle 12 26 42](https://user-images.githubusercontent.com/1274911/27632856-4e9c544c-5bfd-11e7-8251-ccbbf94226f4.png)

thanks
Dennis

**Comment by fashxp** [comment]
could you please retry with latest build.
should work now again.

**Comment by dennistiboni-extera** [comment]
Thanks @fashxp now work fine!
